apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-data-volume
  labels:
    type: local
spec:
  storageClassName: "manual"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/k8s-volumes/blog-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-data-claim
  labels:
    app: wordpress
    type: local
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-mysql-volume
  labels:
    type: local
spec:
  storageClassName: "manual"
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/k8s-volumes/blog-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-mysql-claim
  labels:
    app: wordpress
    type: local
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi