apiVersion: v1
kind: Service
metadata:
  name: wordpress-memcached
  labels:
    app: wordpress
spec:
  ports:
    - port: 11211
  selector:
    app: wordpress-memcached
    tier: frontend
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-memcached
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: memcached:1.5.3
        name: memcached
        ports:
        - containerPort: 11211
          protocol: TCP
