---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  ports:
    - port: 80
  selector:
    app: phpmyadmin
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
 name: phpmyadmin
 labels:
   app: phpmyadmin
spec:
 selector:
   matchLabels:
     app: phpmyadmin
     tier: frontend
 strategy:
   type: Recreate
 template:
   metadata:
     labels:
       app: phpmyadmin
       tier: frontend
   spec:
     containers:
     - image: phpmyadmin/phpmyadmin
       name: phpmyadmin
       env:
       - name: PMA_HOST
         value: 127.0.0.1
       - name: MYSQL_USER
         valueFrom:
           secretKeyRef:
             name: cloudsql-db-credentials
             key: username
       ports:
         - containerPort: 80
     - image: gcr.io/cloudsql-docker/gce-proxy:1.11
       name: cloudsql-proxy
       command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=first-bit-187313:us-east1:mysql-master=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
       volumeMounts:
         - name: cloudsql-instance-credentials
           mountPath: /secrets/cloudsql
           readOnly: true
         - name: ssl-certs
           mountPath: /etc/ssl/certs
         - name: cloudsql
           mountPath: /cloudsql
     volumes:
       - name: cloudsql-instance-credentials
         secret:
           secretName: cloudsql-instance-credentials
       - name: cloudsql
         emptyDir:
       - name: ssl-certs
         hostPath:
           path: /etc/ssl/certs
