apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    app: wordpress-memcached
spec:
  ports:
    - port: 11211
  selector:
    app: wordpress-memcached
    tier: memcached
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: wordpress-memcached
  name: memcached
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: memcached:1.5.3
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30