apiVersion: v1
kind: Pod
metadata:
  name: memcached
  labels:
    name: memcached
spec:
  containers:
    - name: memcached
      image: memcached
      ports:
        - containerPort: 11211
          protocol: TCP
